"""v1 beta

Revision ID: d160bfba1508
Revises: fed50ce4af2b
Create Date: 2021-12-27 09:40:26.871900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd160bfba1508'
down_revision = 'fed50ce4af2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('player')
    op.drop_table('squad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squad',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('global_id', sa.INTEGER(), nullable=True),
    sa.Column('squad_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('formation', sa.VARCHAR(length=10), nullable=True),
    sa.Column('squad_dict', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_id')
    )
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('global_id', sa.INTEGER(), nullable=False),
    sa.Column('rarity', sa.INTEGER(), nullable=False),
    sa.Column('common_name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('lw_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('lf_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('lm_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('lst_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('cst_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('rst_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('cf_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('rw_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('rf_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('rm_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('lcam_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('ccam_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('rcam_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('lcm_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('ccm_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('rcm_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('lcdm_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('ccdm_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('rcdm_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('lwb_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('lb_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('lcb_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('ccb_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('rcb_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('rwb_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('rb_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('gk_meta_rating', sa.INTEGER(), nullable=False),
    sa.Column('nation', sa.INTEGER(), nullable=True),
    sa.Column('nation_str', sa.VARCHAR(length=80), nullable=True),
    sa.Column('league', sa.INTEGER(), nullable=True),
    sa.Column('league_str', sa.VARCHAR(length=80), nullable=True),
    sa.Column('club', sa.INTEGER(), nullable=True),
    sa.Column('club_str', sa.VARCHAR(length=80), nullable=True),
    sa.Column('position', sa.VARCHAR(length=80), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.INTEGER(), nullable=False),
    sa.Column('attack_work_rate', sa.VARCHAR(length=80), nullable=False),
    sa.Column('defense_work_rate', sa.VARCHAR(length=80), nullable=False),
    sa.Column('foot', sa.VARCHAR(length=80), nullable=False),
    sa.Column('weak_foot', sa.INTEGER(), nullable=False),
    sa.Column('skill_moves', sa.INTEGER(), nullable=False),
    sa.Column('shooting', sa.INTEGER(), nullable=False),
    sa.Column('positioning', sa.INTEGER(), nullable=False),
    sa.Column('finishing', sa.INTEGER(), nullable=False),
    sa.Column('shot_power', sa.INTEGER(), nullable=False),
    sa.Column('long_shots', sa.INTEGER(), nullable=False),
    sa.Column('volleys', sa.INTEGER(), nullable=False),
    sa.Column('penalties', sa.INTEGER(), nullable=False),
    sa.Column('defending', sa.INTEGER(), nullable=False),
    sa.Column('heading_accuracy', sa.INTEGER(), nullable=False),
    sa.Column('interceptions', sa.INTEGER(), nullable=False),
    sa.Column('sliding_tackle', sa.INTEGER(), nullable=False),
    sa.Column('standing_tackle', sa.INTEGER(), nullable=False),
    sa.Column('dribbling_face', sa.INTEGER(), nullable=False),
    sa.Column('agility', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.INTEGER(), nullable=False),
    sa.Column('ball_control', sa.INTEGER(), nullable=False),
    sa.Column('composure', sa.INTEGER(), nullable=False),
    sa.Column('dribbling', sa.INTEGER(), nullable=False),
    sa.Column('reactions', sa.INTEGER(), nullable=False),
    sa.Column('pace', sa.INTEGER(), nullable=False),
    sa.Column('acceleration', sa.INTEGER(), nullable=False),
    sa.Column('sprint_speed', sa.INTEGER(), nullable=False),
    sa.Column('passing', sa.INTEGER(), nullable=False),
    sa.Column('crossing', sa.INTEGER(), nullable=False),
    sa.Column('curve', sa.INTEGER(), nullable=False),
    sa.Column('free_kick_accuracy', sa.INTEGER(), nullable=False),
    sa.Column('long_passing', sa.INTEGER(), nullable=False),
    sa.Column('short_passing', sa.INTEGER(), nullable=False),
    sa.Column('vision', sa.INTEGER(), nullable=False),
    sa.Column('physicality', sa.INTEGER(), nullable=False),
    sa.Column('aggression', sa.INTEGER(), nullable=False),
    sa.Column('stamina', sa.INTEGER(), nullable=False),
    sa.Column('jumping', sa.INTEGER(), nullable=False),
    sa.Column('strength', sa.INTEGER(), nullable=False),
    sa.Column('diving', sa.INTEGER(), nullable=True),
    sa.Column('handling', sa.INTEGER(), nullable=True),
    sa.Column('kicking', sa.INTEGER(), nullable=True),
    sa.Column('gk_positioning', sa.INTEGER(), nullable=True),
    sa.Column('reflexes', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=512), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
